name: Clear maximum space
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [20.04]
    name: Run job on ${{ matrix.ubuntu }}
    runs-on: ubuntu-${{ matrix.ubuntu }}
    steps:
      - run: |
             sudo swapoff -a
             sudo rm -f /swapfile
             sudo rm -rf "/usr/local/share/boost"
             sudo rm -rf "$AGENT_TOOLSDIRECTORY"
             sudo rm -rf /usr/share/dotnet/
             sudo rm -rf "$ANDROID_SDK_ROOT"
             sudo rm -rf /usr/local/lib/android
             sudo rm -rf "$SWIFT_PATH"
             sudo rm -rf /usr/share/swift
             sudo rm -rf /usr/lib/node_modules
             sudo docker system prune -a -f
             sudo rm -rf /home/linuxbrew
             ver=$(echo "${{ matrix.ubuntu }}" | sed 's|\.||g')
             wget -qO "toolset.json" "https://raw.githubusercontent.com/actions/virtual-environments/main/images/linux/toolsets/toolset-${ver}.json"
             common_packages=$(jq -r ".apt.common_packages[] | @sh" "toolset.json")
             cmd_packages=$(jq -r ".apt.cmd_packages[] | @sh" "toolset.json")
             sudo apt-get purge -y "${common_packages[@]}"
             sudo apt-get purge -y "${cmd_packages[@]}"
             sudo apt-get -y autoremove
             sudo apt-get -y clean
             df -h
